services:
  cloud-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 2with13/cloud-backend:1.1.3

  cloud-python-ml:
    build:
      context: ./python-ai
      dockerfile: Dockerfile
    image: 2with13/cloud-python-ml:1.1.2
