apiVersion: v1
kind: Service
metadata:
  name: spring-backend
  namespace: moodtracker
spec:
  selector:
    app: spring-backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: moodtracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: 2with13/cloud-backend:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/moodtracker
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: pswd
