apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-ml-hpa
  namespace: moodtracker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-ml           # Deployment 이름
  minReplicas: 1
  maxReplicas: 5              # 늘어날 수 있는 최대 파드 수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # CPU 사용률이 75%를 넘으면 스케일 아웃