apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodtracker-ingress
  namespace: moodtracker
spec:
  rules:
    - host: moodtracker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-backend
                port:
                  number: 8080