apiVersion: v1
kind: Service
metadata:
  name: python-ml
  namespace: moodtracker
spec:
  selector:
    app: python-ml
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ml
  namespace: moodtracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-ml
  template:
    metadata:
      labels:
        app: python-ml
    spec:
      containers:
        - name: python-ml
          image: 2with13/cloud-python-ml:1.0.1
          ports:
            - containerPort: 8000
