apiVersion: v1
kind: Secret
metadata:
  name: spotify-secret
  namespace: moodtracker
type: Opaque
data:
  # base64로 암호화됨
  SPOTIPY_CLIENT_ID: NjkzZjBhZjZlZTllNDBkZTg1OGJhMGI4ODJkOTRhNjA=
  SPOTIPY_CLIENT_SECRET: NDllNjQ3YmE1MjNmNGRmYWFlNTYxNWYyOWM5YmY4OTM=

